kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-schema
data:
  redis_schema.yaml: |
    numeric:
    - name: page
      no_index: false
      sortable: false
    text:
    - name: source
      no_index: false
      no_stem: false
      sortable: false
      weight: 1
      withsuffixtrie: false
    - name: content
      no_index: false
      no_stem: false
      sortable: false
      weight: 1
      withsuffixtrie: false
    vector:
    - algorithm: FLAT
      block_size: 1000
      datatype: FLOAT32
      dims: 768
      distance_metric: COSINE
      initial_cap: 20000
      name: content_vector
