# Generated by Selenium IDE
# import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions  as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.common.exceptions import TimeoutException

# read yaml file
# loop 
driver = webdriver.Firefox()
vars = {}

driver.get("https://gradio-hftgi-rag-redis-vectordb.apps.ai-dev01.kni.syseng.devcluster.openshift.com")
driver.set_window_size(1084, 811)
timeout = 10
try:
    # element_present = EC.presence_of_element_located((By.CSS_SELECTOR, "#chatinput .scroll-hide"))
    element_present = EC.presence_of_element_located((By.CSS_SELECTOR, "#component-1 .scroll-hide"))
    WebDriverWait(driver, timeout).until(element_present)
except TimeoutException:
    print("Timed out waiting for page to load")

driver.find_element(By.CSS_SELECTOR, "#component-1 .scroll-hide")
driver.find_element(By.CSS_SELECTOR, "#component-1 .scroll-hide").send_keys("hi how are you")
driver.find_element(By.ID, "component-12").click()

label_id="label[data-testid='2-radio-label']"
x = WebDriverWait(driver, 20).until(EC.visibility_of_element_located((By.CSS_SELECTOR, label_id))).click()

# if needed add some delay
# driver.quit()
# end loop
