# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classificationresults.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import classificationresult_pb2 as classificationresult__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63lassificationresults.proto\x12\x15\x63\x61ikit_data_model.nlp\x1a\x1a\x63lassificationresult.proto\"U\n\x15\x43lassificationResults\x12<\n\x07results\x18\x01 \x03(\x0b\x32+.caikit_data_model.nlp.ClassificationResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classificationresults_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CLASSIFICATIONRESULTS']._serialized_start=82
  _globals['_CLASSIFICATIONRESULTS']._serialized_end=167
# @@protoc_insertion_point(module_scope)
