# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: textclassificationtaskrequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#textclassificationtaskrequest.proto\x12\x12\x63\x61ikit.runtime.Nlp\"-\n\x1dTextClassificationTaskRequest\x12\x0c\n\x04text\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'textclassificationtaskrequest_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TEXTCLASSIFICATIONTASKREQUEST']._serialized_start=59
  _globals['_TEXTCLASSIFICATIONTASKREQUEST']._serialized_end=104
# @@protoc_insertion_point(module_scope)
