# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tokenclassificationresult.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ftokenclassificationresult.proto\x12\x15\x63\x61ikit_data_model.nlp\"\x8f\x01\n\x19TokenClassificationResult\x12\r\n\x05start\x18\x01 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x03\x12\x0c\n\x04word\x18\x03 \x01(\t\x12\x0e\n\x06\x65ntity\x18\x04 \x01(\t\x12\x14\n\x0c\x65ntity_group\x18\x05 \x01(\t\x12\r\n\x05score\x18\x06 \x01(\x01\x12\x13\n\x0btoken_count\x18\x07 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tokenclassificationresult_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TOKENCLASSIFICATIONRESULT']._serialized_start=59
  _globals['_TOKENCLASSIFICATIONRESULT']._serialized_end=202
# @@protoc_insertion_point(module_scope)
