# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tokenstreamdetails.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import finishreason_pb2 as finishreason__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18tokenstreamdetails.proto\x12\x15\x63\x61ikit_data_model.nlp\x1a\x12\x66inishreason.proto\"\x93\x01\n\x12TokenStreamDetails\x12:\n\rfinish_reason\x18\x01 \x01(\x0e\x32#.caikit_data_model.nlp.FinishReason\x12\x18\n\x10generated_tokens\x18\x02 \x01(\r\x12\x0c\n\x04seed\x18\x03 \x01(\x04\x12\x19\n\x11input_token_count\x18\x04 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tokenstreamdetails_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TOKENSTREAMDETAILS']._serialized_start=72
  _globals['_TOKENSTREAMDETAILS']._serialized_end=219
# @@protoc_insertion_point(module_scope)
