# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tokenclassificationstreamresult.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tokenclassificationresult_pb2 as tokenclassificationresult__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%tokenclassificationstreamresult.proto\x12\x15\x63\x61ikit_data_model.nlp\x1a\x1ftokenclassificationresult.proto\"}\n\x1fTokenClassificationStreamResult\x12\x41\n\x07results\x18\x01 \x03(\x0b\x32\x30.caikit_data_model.nlp.TokenClassificationResult\x12\x17\n\x0fprocessed_index\x18\x02 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tokenclassificationstreamresult_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TOKENCLASSIFICATIONSTREAMRESULT']._serialized_start=97
  _globals['_TOKENCLASSIFICATIONSTREAMRESULT']._serialized_end=222
# @@protoc_insertion_point(module_scope)
