# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bidistreamingtokenclassificationtaskrequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1bidistreamingtokenclassificationtaskrequest.proto\x12\x12\x63\x61ikit.runtime.Nlp\"h\n+BidiStreamingTokenClassificationTaskRequest\x12\x13\n\x0btext_stream\x18\x01 \x01(\t\x12\x16\n\tthreshold\x18\x02 \x01(\x01H\x00\x88\x01\x01\x42\x0c\n\n_thresholdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bidistreamingtokenclassificationtaskrequest_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BIDISTREAMINGTOKENCLASSIFICATIONTASKREQUEST']._serialized_start=73
  _globals['_BIDISTREAMINGTOKENCLASSIFICATIONTASKREQUEST']._serialized_end=177
# @@protoc_insertion_point(module_scope)
