# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exponentialdecaylengthpenalty.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#exponentialdecaylengthpenalty.proto\x12\x1c\x63\x61ikit_data_model.caikit_nlp\"J\n\x1d\x45xponentialDecayLengthPenalty\x12\x13\n\x0bstart_index\x18\x01 \x01(\x03\x12\x14\n\x0c\x64\x65\x63\x61y_factor\x18\x02 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exponentialdecaylengthpenalty_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EXPONENTIALDECAYLENGTHPENALTY']._serialized_start=69
  _globals['_EXPONENTIALDECAYLENGTHPENALTY']._serialized_end=143
# @@protoc_insertion_point(module_scope)
