# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: textgenerationtaskrequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import exponentialdecaylengthpenalty_pb2 as exponentialdecaylengthpenalty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ftextgenerationtaskrequest.proto\x12\x12\x63\x61ikit.runtime.Nlp\x1a#exponentialdecaylengthpenalty.proto\"\xe0\x05\n\x19TextGenerationTaskRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x1b\n\x0emax_new_tokens\x18\x02 \x01(\x03H\x00\x88\x01\x01\x12\x1b\n\x0emin_new_tokens\x18\x03 \x01(\x03H\x01\x88\x01\x01\x12\"\n\x15truncate_input_tokens\x18\x04 \x01(\x03H\x02\x88\x01\x01\x12\x1c\n\x0f\x64\x65\x63oding_method\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x12\n\x05top_k\x18\x06 \x01(\x03H\x04\x88\x01\x01\x12\x12\n\x05top_p\x18\x07 \x01(\x01H\x05\x88\x01\x01\x12\x16\n\ttypical_p\x18\x08 \x01(\x01H\x06\x88\x01\x01\x12\x18\n\x0btemperature\x18\t \x01(\x01H\x07\x88\x01\x01\x12\x11\n\x04seed\x18\n \x01(\x04H\x08\x88\x01\x01\x12\x1f\n\x12repetition_penalty\x18\x0b \x01(\x01H\t\x88\x01\x01\x12\x15\n\x08max_time\x18\x0c \x01(\x01H\n\x88\x01\x01\x12j\n exponential_decay_length_penalty\x18\r \x01(\x0b\x32;.caikit_data_model.caikit_nlp.ExponentialDecayLengthPenaltyH\x0b\x88\x01\x01\x12\x16\n\x0estop_sequences\x18\x0e \x03(\t\x12 \n\x13preserve_input_text\x18\x0f \x01(\x08H\x0c\x88\x01\x01\x42\x11\n\x0f_max_new_tokensB\x11\n\x0f_min_new_tokensB\x18\n\x16_truncate_input_tokensB\x12\n\x10_decoding_methodB\x08\n\x06_top_kB\x08\n\x06_top_pB\x0c\n\n_typical_pB\x0e\n\x0c_temperatureB\x07\n\x05_seedB\x15\n\x13_repetition_penaltyB\x0b\n\t_max_timeB#\n!_exponential_decay_length_penaltyB\x16\n\x14_preserve_input_textb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'textgenerationtaskrequest_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TEXTGENERATIONTASKREQUEST']._serialized_start=93
  _globals['_TEXTGENERATIONTASKREQUEST']._serialized_end=829
# @@protoc_insertion_point(module_scope)
