# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tokenclassificationresults.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tokenclassificationresult_pb2 as tokenclassificationresult__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n tokenclassificationresults.proto\x12\x15\x63\x61ikit_data_model.nlp\x1a\x1ftokenclassificationresult.proto\"_\n\x1aTokenClassificationResults\x12\x41\n\x07results\x18\x01 \x03(\x0b\x32\x30.caikit_data_model.nlp.TokenClassificationResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tokenclassificationresults_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TOKENCLASSIFICATIONRESULTS']._serialized_start=92
  _globals['_TOKENCLASSIFICATIONRESULTS']._serialized_end=187
# @@protoc_insertion_point(module_scope)
