ARG BASE_IMAGE=quay.io/sclorg/python-312-c9s:c9s

FROM ${BASE_IMAGE}

USER 0

###################################################################################################
# OS Layer                                                                                        #
###################################################################################################

RUN --mount=type=bind,source=common/os-packages.txt,target=/tmp/os-packages.txt \
    dnf -y install --best --nodocs --setopt=install_weak_deps=False dnf-plugins-core && \
    dnf config-manager --best --nodocs --setopt=install_weak_deps=False --save && \
    dnf config-manager --enable crb && \
    dnf -y update && \
    dnf install -y $(cat /tmp/os-packages.txt) && \
    dnf -y clean all && \
    rm -rf /var/cache/dnf

ENV TESSDATA_PREFIX=/usr/share/tesseract/tessdata/

###################################################################################################
# Docling layer                                                                                   #
###################################################################################################

USER 1001

WORKDIR /opt/app-root/src

RUN --mount=type=bind,source=cpu/requirements.txt,target=/tmp/requirements.txt \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r /tmp/requirements.txt && \
    chmod -R g+w /opt/app-root/lib/python3.12/site-packages && \
    fix-permissions /opt/app-root -P
 
RUN --mount=type=bind,source=common/models-download.py,target=/tmp/models-download.py \
    mkdir -p /opt/app-root/src/.EasyOCR/model && \
    python /tmp/models-download.py && \
    chmod -R g+w /opt/app-root/src && \
    fix-permissions /opt/app-root -P

COPY --chown=1001:0 --chmod=664 common/app.py .

CMD ["python", "app.py"]
