ARG GOLANG_VERSION=1.22.1

# Create a container with Git repo
FROM --platform=linux/amd64 quay.io/centos/centos:stream9 as repo
WORKDIR /
RUN yum -y update && \
    yum -y install git && \
    git clone https://github.com/ollama/ollama.git && \
    cd ollama && \
    git checkout tags/v0.1.29

# Copy the minimal context we need to run the generate scripts
FROM scratch AS llm-code
COPY --from=repo /ollama/.git .git
COPY --from=repo /ollama/.gitmodules .gitmodules
COPY --from=repo /ollama/llm llm

FROM --platform=linux/amd64 quay.io/centos/centos:stream9 AS cpu-builder-amd64
ARG GOLANG_VERSION
RUN yum -y update && \
    yum -y install gcc-c++ cmake gcc-toolset-13 git && \
    mkdir -p /usr/local && \
    curl -s -L https://dl.google.com/go/go${GOLANG_VERSION}.linux-amd64.tar.gz | tar xz -C /usr/local && \
    ln -s /usr/local/go/bin/go /usr/local/bin/go && \
    ln -s /usr/local/go/bin/gofmt /usr/local/bin/gofmt
COPY --from=llm-code / /go/src/github.com/jmorganca/ollama/
WORKDIR /go/src/github.com/jmorganca/ollama/llm/generate

FROM --platform=linux/amd64 cpu-builder-amd64 AS cpu-build-amd64
RUN OLLAMA_CPU_TARGET="cpu" sh gen_linux.sh
FROM --platform=linux/amd64 cpu-builder-amd64 AS cpu_avx2-build-amd64
RUN OLLAMA_CPU_TARGET="cpu_avx2" sh gen_linux.sh

# Intermediate stage used for ./scripts/build_linux.sh
FROM --platform=linux/amd64 cpu-build-amd64 AS build-amd64
ENV CGO_ENABLED 1
WORKDIR /go/src/github.com/jmorganca/ollama
COPY --from=repo /ollama/ .
COPY --from=cpu_avx2-build-amd64 /go/src/github.com/jmorganca/ollama/llm/llama.cpp/build/linux/ llm/llama.cpp/build/linux/
RUN go build -trimpath .

# Runtime stages
FROM --platform=linux/amd64 registry.access.redhat.com/ubi9:latest as runtime-amd64
RUN yum -y update && \
    yum -y clean all --enablerepo='*' && \
    rm -rf /var/cache/dnf && \
    find /var/log -type f -name "*.log" -exec rm -f {} \;
COPY --from=build-amd64 /go/src/github.com/jmorganca/ollama/ollama /bin/ollama

FROM runtime-amd64
EXPOSE 11434
ENV OLLAMA_HOST 0.0.0.0
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

ENTRYPOINT ["/bin/ollama"]
CMD ["serve"]