FROM registry.access.redhat.com/ubi9/python-312

USER 0

RUN yum -y update && \
    yum -y clean all && \
    rm -rf /var/cache/yum

USER 1001

WORKDIR /opt/app-root/src

COPY requirements.txt /opt/app-root/src/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt && \
    rm -f requirements.txt && \
    # Fix permissions to support pip in Openshift environments \
    chmod -R g+w /opt/app-root/lib/python3.12/site-packages && \
    fix-permissions /opt/app-root -P

COPY --chown=1001:0 app.py /opt/app-root/src/app.py

USER 1001

EXPOSE 8080

ENTRYPOINT ["python3", "app.py"]