FROM registry.access.redhat.com/ubi9/python-311

USER 0

RUN yum -y update && \
    yum -y clean all && \
    rm -rf /var/cache/yum

USER 1001

COPY frozen-requirements.txt .

RUN pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir -r frozen-requirements.txt


EXPOSE 8080

ENTRYPOINT ["deepsparse.server"]